### ISSUE TITLE
mip installs to lib/servo instead of lib/dfplayer

### ISSUE THREAD

**Issue by scruss** [redoxcode/micropython-dfplayer#5]
Minor typo in your `package.json` causes the package to be installed in the wrong place. I'll create a PR for this

**Comment by scruss** [comment]
PR is [Install path changed from lib/servo to lib/dfplayer by scruss · Pull Request #6 · redoxcode/micropython-dfplayer](https://github.com/redoxcode/micropython-dfplayer/pull/6)

**Comment by redoxcode** [comment]
Thank you! 
Must have been a copy paste error.
Closed with PR https://github.com/redoxcode/micropython-dfplayer/pull/6
